"""
Orchestrator Agent - Synthesizes findings, provides an executive summary,
and acts as the final gatekeeper to ensure the report is foolproof.
"""

import json
import logging
import os
from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage, HumanMessage

logger = logging.getLogger(__name__)

class OrchestratorAgent:
    """
    Synthesizes the final output from all specialist agents.
    Provides an executive summary, critical risk assessment, and
    architectural recommendations to make the audit report foolproof.
    """
    agent_name = "orchestrator"

    system_prompt = """You are an elite Lead Security Architect and Audit Orchestrator.
Your objective is to review a list of security and code quality findings generated by various specialist agents, synthesize them into a foolproof executive summary, and provide a high-level architectural health score.

## Your Mandates:
1. **Synthesize & Prioritize**: Group related findings into systemic issues (e.g., "Widespread lack of input validation" instead of 10 individual XSS issues).
2. **Executive Summary**: Write a concise, hard-hitting executive summary suitable for a CTO or Lead Engineer.
3. **Architectural Health**: Score the overall architecture out of 100 based on the findings.

Respond strictly with a JSON object containing:
- `executive_summary`: A 2-3 paragraph markdown string summarizing the risk posture.
- `systemic_issues`: An array of strings describing overarching themes or repeated patterns of failure.
- `health_score`: An integer from 0 to 100.
- `key_recommendations`: An array of 3-5 high-level actionable steps to secure the codebase.

IMPORTANT: Respond with ONLY the valid JSON object. Do not include markdown formatting like ```json, do not include any text or explanations outside the JSON."""

    def __init__(self, model_name: str | None = None, temperature: float = 0.2):
        if not model_name:
            model_name = os.environ.get("OPENAI_MODEL", "gpt-5.4-mini")
        self.llm = ChatOpenAI(model=model_name, temperature=temperature)

    async def synthesize(self, aggregated_findings: list[dict]) -> dict:
        """
        Analyze all findings and generate an executive summary.
        """
        if not aggregated_findings:
            return {
                "executive_summary": "No vulnerabilities or issues were detected. The codebase appears to be in excellent condition.",
                "systemic_issues": [],
                "health_score": 100,
                "key_recommendations": ["Continue maintaining current security practices."]
            }

        # Extract high-level summary to avoid overwhelming context limits
        critical_findings = [f for f in aggregated_findings if f.get("severity") in ("EXTREME", "HIGH")]
        other_findings = [f for f in aggregated_findings if f.get("severity") in ("MEDIUM", "LOW")]

        # Cap the samples we send to the LLM to keep context size manageable
        if len(critical_findings) > 30:
            critical_findings = critical_findings[:30]
        if len(other_findings) > 20:
            other_findings = other_findings[:20]

        summary_data = {
            "total_findings_count": len(aggregated_findings),
            "critical_findings_count": len(critical_findings),
            "other_findings_count": len(other_findings),
            "critical_samples": [
                {"title": f.get("title"), "bug_type": f.get("bug_type"), "agent": f.get("agent", "unknown")}
                for f in critical_findings
            ],
            "other_samples": [
                {"title": f.get("title"), "bug_type": f.get("bug_type"), "agent": f.get("agent", "unknown")}
                for f in other_findings
            ]
        }

        user_prompt = f"""Review the following summary of findings detected in the repository:

```json
{json.dumps(summary_data, indent=2)}
```

Generate the foolproof executive report as requested."""

        messages = [
            SystemMessage(content=self.system_prompt),
            HumanMessage(content=user_prompt),
        ]

        try:
            response = await self.llm.ainvoke(messages)
            cleaned = response.content.strip()

            # Robust JSON extraction
            start_idx = cleaned.find('{')
            end_idx = cleaned.rfind('}')
            if start_idx != -1 and end_idx != -1 and end_idx >= start_idx:
                cleaned = cleaned[start_idx:end_idx+1]

            result = json.loads(cleaned)
            return result
        except Exception as e:
            logger.error(f"[Orchestrator] Failed to synthesize report: {e}")
            logger.debug(f"[Orchestrator] Raw response: {response.content if 'response' in locals() else 'N/A'}")
            return {
                "executive_summary": "An error occurred while synthesizing the executive summary.",
                "systemic_issues": [],
                "health_score": 0,
                "key_recommendations": []
            }
